#!/usr/bin/env python3
"""Build the repository homepage README from the four language source files."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "README.md"
SECTIONS = (
    ("zh-hans", ROOT / "README.zh-Hans.md"),
    ("zh-hant", ROOT / "README.zh-Hant.md"),
    ("ja", ROOT / "README.ja.md"),
    ("en", ROOT / "README.en.md"),
)
NAVIGATION = (
    "[简体中文](#zh-hans) | [繁體中文](#zh-hant) | "
    "[日本語](#ja) | [English](#en)"
)


def source_body(path: Path) -> tuple[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 5 or not lines[0].startswith("# "):
        raise ValueError(f"Unexpected README source structure: {path.name}")
    if lines[1] or lines[3]:
        raise ValueError(f"Expected blank lines around language navigation: {path.name}")
    return lines[0], "\n".join(lines[4:]).rstrip()


def render() -> str:
    sections = []
    for anchor, path in SECTIONS:
        title, body = source_body(path)
        sections.append(
            f'<a id="{anchor}"></a>\n\n{title}\n\n{NAVIGATION}\n\n{body}'
        )
    notice = (
        "<!-- Generated by tools/build_multilingual_readme.py; "
        "edit README.*.md sources. -->"
    )
    return notice + "\n\n" + "\n\n---\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "README.md is out of date; run tools/build_multilingual_readme.py"
            )
        print("README.md is synchronized with all language sources.")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print("Generated README.md with in-page language navigation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
